### ISSUE TITLE
CSS框架的设计

### ISSUE THREAD

**Issue by RubyLouvre** [RubyLouvre/avalon.oniui#349]
先定义一个英文字体再定义中文字体，这是因为英文字体中一般不含有中文，执行的时候英文和阿拉伯数字选用“Arial”,中文的字体使用第二个字体“微软雅黑”。比如，可以这样来定义WordPress中的中英文字体：

``` css
body{
    font-family: Arial,"微软雅黑";
}
```

*需要注意的是，这样的做法对符合网页规范的浏览器比如Firefox虽然有效，但对IE6、IE7会导致中文字体设定无效，也就是说，这样的办法对于微软的IE系列来说等于不设置中文字体，而只是采用系统默认的“宋体”来显示网页内容。

也可以指定两个class分别分配给中文和英文内容，这样就可以对IE也实现如上的字体效果，并可以为中英文的显示进行更详细的定制（比如字号等属性），但缺点是这样的做法比较繁杂，使用上不太方便，特别是对博客这样的中英文混编的文章内容来说更是麻烦。
